### ISSUE TITLE
Tag a new release to enable custom_args

### ISSUE THREAD

**Issue by natemccurdy** [joshbeard/puppet-display#12]
Custom arguments have been put into master branch, but the Forge module doesn't have these enhancements because a new release hasn't been tagged.

**Comment by joshbeard** [comment]
Pushed up 0.5.0 that adds the custom arguments.  https://forge.puppetlabs.com/joshbeard/display/0.5.0

Sorry for the delay.  I was sitting on this because I wanted to do something specific for passwords, as described in https://github.com/joshbeard/puppet-display/issues/11, but that's less than trivial to do it sanely.
